//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> <IDENTIFIER>
 */
public class Identifier implements Node {
   public NodeToken f0;
   public String id_value;
   public Identifier(NodeToken n0) {
      f0 = n0;
      id_value = n0.toString();
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return choice_num;
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return choice_num;
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}
