//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> ClassDeclaration()
 *       | ClassExtendsDeclaration()
 */
public class TypeDeclaration implements Node {
   public NodeChoice f0;
   public int typedeclaration_choice;
   
   public TypeDeclaration(TypeDeclaration xyz_1){
       f0 = xyz_1.f0;
       typedeclaration_choice = xyz_1.typedeclaration_choice;
   }
   public TypeDeclaration(NodeChoice n0) {
      f0 = n0;
      typedeclaration_choice = n0.which;
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}
